# Generated by Django 4.0.4 on 2022-05-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0004_alter_imagen_imagen'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='imagen',
            name='unique_profile_picture',
        ),
        migrations.AddConstraint(
            model_name='imagen',
            constraint=models.UniqueConstraint(fields=('perfil', 'is_profile_picture'), name='unique_profile_picture'),
        ),
    ]
