# Generated by Django 4.2.7 on 2023-11-22 00:42

from django.db import migrations, models
from django.utils.crypto import get_random_string


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0007_perfil_codigo_de_activacion_alter_imagen_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='codigo_de_activacion',
            field=models.CharField(get_random_string(length=10), max_length=10),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='numero_de_telefono',
            field=models.CharField(blank=True, help_text='Este número podría servir para contactar a su humano en caso de que se extravíe.', max_length=50, null=True),
        ),
    ]
