# Generated by Django 5.0.3 on 2024-03-18 23:17

import perfiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0008_alter_perfil_codigo_de_activacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='codigo_de_activacion',
            field=models.CharField(default=perfiles.models.generate_random_string, max_length=10),
        ),
    ]
